import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import AuthContext from '@/context/AuthContext'
import ToastContext from '@/context/ToastContext'

import { ThemeProvider } from '@/components/providers/theme-provider'
import { ModalProvider } from '@/components/providers/modal-provider'
import { SocketProvider } from '@/components/providers/socket-provider'

import { cn } from '@/lib/utils'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(openSans.className, 'bg-white dark:bg-[#313338]')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          storageKey="discord-theme"
        >
          <SocketProvider>
            <AuthContext>
              <ModalProvider />
              <ToastContext />
              {children}
            </AuthContext>
          </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
