import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import AuthContext from '@/context/AuthContext'
import ToastContext from '@/context/ToastContext'

import { ThemeProvider } from '@/components/providers/theme-provider'
import { ModalProvider } from '@/components/providers/modal-provider'

import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, 'bg-white dark:bg-[#313338]')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          storageKey="discord-theme"
        >
          <AuthContext>
            <ModalProvider />
            <ToastContext />
            {children}
          </AuthContext>
        </ThemeProvider>
      </body>
    </html>
  )
}
